// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6AAgtGXuB1HqYi5SPd--NciK257dn3yQ',
    appId: '1:1011851644960:web:e6693c27a34888e8782c45',
    messagingSenderId: '1011851644960',
    projectId: 'test-d901d',
    authDomain: 'test-d901d.firebaseapp.com',
    storageBucket: 'test-d901d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU5J6v0URpPtpEq6y_C8WS23WQ-bEDcks',
    appId: '1:1011851644960:android:776bab4cbbdf27ee782c45',
    messagingSenderId: '1011851644960',
    projectId: 'test-d901d',
    storageBucket: 'test-d901d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZg7YneBW4CrHKOn72jfepsZWOEAmdoWY',
    appId: '1:1011851644960:ios:7c402051ac980452782c45',
    messagingSenderId: '1011851644960',
    projectId: 'test-d901d',
    storageBucket: 'test-d901d.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZg7YneBW4CrHKOn72jfepsZWOEAmdoWY',
    appId: '1:1011851644960:ios:7c402051ac980452782c45',
    messagingSenderId: '1011851644960',
    projectId: 'test-d901d',
    storageBucket: 'test-d901d.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6AAgtGXuB1HqYi5SPd--NciK257dn3yQ',
    appId: '1:1011851644960:web:e1352a8175b38f9a782c45',
    messagingSenderId: '1011851644960',
    projectId: 'test-d901d',
    authDomain: 'test-d901d.firebaseapp.com',
    storageBucket: 'test-d901d.firebasestorage.app',
  );
}
